version: "3.9"

services:
  mcp-endpoint:
    build:
      context: ./mcp-endpoint-example
    image: armoriq-mcp-endpoint:local
    ports:
      - "${MCP_ENDPOINT_HOST_PORT:-3001}:3001"

  armoriq-proxy:
    build:
      context: ./armoriq-proxy
    image: armoriq-proxy:local
    environment:
      MCP_ENDPOINT_URL: http://mcp-endpoint:3001
    ports:
      - "${ARMORIQ_PROXY_HOST_PORT:-5001}:5001"
    depends_on:
      - mcp-endpoint

  admin-api:
    build:
      context: ./admin-api
    image: armoriq-admin-api:local
    environment:
      ARMORIQ_PROXY_URL: http://armoriq-proxy:5001
    ports:
      - "${ADMIN_API_HOST_PORT:-8000}:8000"
    depends_on:
      - armoriq-proxy

  agent:
    build:
      context: ./agent-example
    image: armoriq-agent:local
    environment:
      ARMORIQ_PROXY_URL: http://armoriq-proxy:5001
      ARMORIQ_API_KEY: ${ARMORIQ_API_KEY:-demo-key-12345678901234567890}
      AGENT_ID: ${AGENT_ID:-agent-123}
      ENDPOINT_ID: ${ENDPOINT_ID:-customer-data-service}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - armoriq-proxy
